### ISSUE TITLE
"tools" folder is missing in the repository

### ISSUE THREAD

**Issue by kr-sundaram** [cbaziotis/lm-prior-for-nmt#1]
Great works! Your findings are really appreciable.

When performing the data preprocessing by myself, I found that the "tools" directory is missing in this repository. It will be very helpful if you could upload that too?

Please find the screenshot of preprocessing shell script where you have written code about the same.

![github_tools_folder_issue](https://user-images.githubusercontent.com/49531274/84391825-c6477680-abf9-11ea-8f1e-aa3044255121.PNG)

**Comment by cbaziotis** [comment]
Sorry about that. I forgot about it during refactoring. It must be solved with this commit https://github.com/cbaziotis/lm-prior-for-nmt/commit/a442800bb0d792f42124925e1256eb30a5cc8321.

**Comment by kr-sundaram** [comment]
Thank you very much! Your work is really good and appreciable!
