### ISSUE TITLE
Inference model is missing.

### ISSUE THREAD

**Issue by kr-sundaram** [cbaziotis/lm-prior-for-nmt#2]
Hi, Thanks for making this repo public. Could you please add scripts for generating the translations to the repository i.e. the evaluation and  inference scripts as it is not present in the current repository?

**Comment by kr-sundaram** [comment]
Hello,

I am doing research on how to handle low-resource data in order to develop a robust machine translation model and i need your inputs in order to understand your implementation as i am not able to execute the code in my computer and receiving errors.

Below are the steps that i follow to train the model.

1. Run Visdom server
   a. I ran the visdom server with 'python -m visdom.server'.

2. To train the language model of the target side.
    a. I tried to train the language model of the target side but received below error.
![error_nmt_prior](https://user-images.githubusercontent.com/49531274/87581446-3eadc580-c6d9-11ea-8267-18d496a52314.jpg)

3. I looked into the code and found that instead of training the language model on target side language, we can use the GPT-2 pretrained model as the language model. I tried to train Translation model with this setting but received the same error. I am attaching the whole error herewith with the comment.

Please let me know in case you need more input.

Thanks for your patience!!
[error_nmt_prior.txt](https://github.com/cbaziotis/lm-prior-for-nmt/files/4927220/error_nmt_prior.txt)


Note: Even if i don't run Visdom server and tried to train any model i.e. Language or Translation model, i receive the same error.

**Comment by cbaziotis** [comment]
Hi,
Sorry for the late reply. First, I see that you are using pytrorch 1.5, but as mentioned in the readme, the project was developed in version 1.4. Can you try with pytorch 1.4? 
You are also using windows and I am not sure if this causes any problems. I don't have a machine with windows to test the implementation.

Can you try starting visdom with `visdom -port 8096`?  Also, what python version are you using? 

I will add a script to download all the checkpoints for the LMs used in our experiments, so you don't have to train an LM to reproduce the results.

Regarding GPT-2, as I mentioned in the paper, I didn't observe any gains and on top of that, it is much slower.

To generate translations with using the checkpoint from a TM and optionally an LM (prior/fusion), you can use [lm-prior-for-nmt/models/translate.py](https://github.com/cbaziotis/lm-prior-for-nmt/blob/master/models/translate.py).

**Update**: see the updated README.md with instructions to download the pretrained LMs.

**Comment by cbaziotis** [comment]
I am closing the issue. Please reopen it if the issue persists.
