### ISSUE TITLE
can not import name:eval_nmt_checkpoint

### ISSUE THREAD

**Issue by conquerSelf** [cbaziotis/lm-prior-for-nmt#3]
when i run your code,i meet the above error.Can you help me to solve it?Thanks a lot.

**Comment by conquerSelf** [comment]
Traceback (most recent call last):
  File "nmt_prior.py", line 9, in <module>
    from models.nmt_prior_callbacks import EvalCallback, SamplesCallback, \
  File "./models/nmt_prior_callbacks.py", line 12, in <module>
    from models.translate import seq2seq_translate_ids, \
  File "./models/translate.py", line 18, in <module>
    from models.nmt_prior_helpers import prior_model_from_checkpoint
  File "./models/nmt_prior_helpers.py", line 24, in <module>
    from models.translate import eval_nmt_checkpoint, seq2seq_translate
ImportError: cannot import name 'eval_nmt_checkpoint'

this is my complete error output!

**Comment by cbaziotis** [comment]
Please give more details. First of all, what is the command that you are running?

**Comment by cbaziotis** [comment]
Reopen the issue, if you are still facing problems.
