### ISSUE TITLE
Why I got BLUE 0.0 and the generated translation file is empty

### ISSUE THREAD

**Issue by hischen** [cbaziotis/lm-prior-for-nmt#4]
Fabulous work and paper！
I'd like to train a EN-DE translation model based on your code. First, I train a DE LM, Then I train a EN-DE TM with LM prior,but I got  BLEU 0.0 on val and test, is there something wrong I have made? My environment is  same as yours.

Thanks for your patience!!

**Comment by Frankszc** [comment]
Hi, I'm sorry to disturb you. 
I am wondering which python file is used when training the language model. I can't find the "mono_sent.py".

Thanks a lot!!!

**Comment by Frankszc** [comment]
> Fabulous work and paper！
> I'd like to train a EN-DE translation model based on your code. First, I train a DE LM, Then I train a EN-DE TM with LM prior,but I got BLEU 0.0 on val and test, is there something wrong I have made? My environment is same as yours.
> 
> Thanks for your patience!!

Hi, I'm sorry to disturb you.
I am wondering which python file is used when training the language model. I can't find the "mono_sent.py".

Thanks a lot!!!

**Comment by cbaziotis** [comment]
Hi! Thanks for pointing this out! I introduced a bug when I refactored the code before pushing it to github. I think I fixed it. Please also read the updated documentation. 

Let me know if it works now.

**Comment by liuqingpu** [comment]
Thanks,I will try it
