### ISSUE TITLE
Where is the "mono_sent.py" file?

### ISSUE THREAD

**Issue by Frankszc** [cbaziotis/lm-prior-for-nmt#5]
Thanks for your great work!
I am wondering where is the "mono_sent.py"(the file used for training the language model)?

Looking forward to your reply!

**Comment by cbaziotis** [comment]
The REAME was wrong, the correct file is `models/sent_lm.py`. I fixed it. Please, read the updated documentation.

**Comment by Frankszc** [comment]
> The REAME was wrong, the correct file is `models/sent_lm.py`. I fixed it. Please, read the updated documentation.

Thanks！And which task is used to train the language model? The masked language taks like bert?
